baseURL = "https://italovietro.com/"
title = "Italo Vietro"
theme = "minimal"
languagecode = "en-US" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

canonifyurls = true # Enable to turn relative URLs into absolute.
enableRobotsTXT = true
googleAnalytics = "UA-5628814-4"

[params]
    author = "Italo Vietro"
    description = "SRE Enthusiast, Distributed Systems Engineer, and Coffee Lover"
    githubUsername = "italolelis"
    accent = "red"
    showBorder = false
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "php"]
    favicon = "images/fav.ico"
    copyright = "&copy; All rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)"
    profilePic = "images/profile.jpg"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/manager"
    name = "Manager"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://github.com/italolelis/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/italolelis/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/italolelis/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/story/italolelis"
    name = "stack-overflow"
    weight = 5

[[menu.icon]]
    url = "https://medium.com/@italolelis"
    name = "medium"
    weight = 6

